### ISSUE TITLE
那个 chrome 工具是怎么弄的呀

### ISSUE THREAD

**Issue by foreverZ133** [chenzhuo1992/easycanvas#1]
如题，先行谢过。商城里并没有搜到。

机型为 win10 的 chrome63

**Comment by chenzhuo1992** [comment]
clone仓库之后，打开Chrome://extensions，然后点击“加载已解压的扩展程序”，选择仓库里的/plugin/dist目录就可以了
目前还没有放到商城里，过一段会发布

**Comment by QJesus** [comment]
chrome 76.0.3809.132

按如上步骤安装后，F12 中未出现 Easycanvas 选项卡
![image](https://user-images.githubusercontent.com/9971413/64495728-5bff4f80-d2d0-11e9-94bb-0add91627b02.png)
"easy-canvas not detected"

**Comment by c-zhuo** [comment]
@QJesus 这个是安装成功了，但是没有在页面里找到Easycanvas的dev版本。
