### ISSUE TITLE
微信小游戏兼容问题

### ISSUE THREAD

**Issue by maxtcarry** [chenzhuo1992/easycanvas#5]
代码是没有进行 微信小游戏适配吗？

**Comment by chenzhuo1992** [comment]
小游戏的话需要引入https://developers.weixin.qq.com/minigame/dev/tutorial/base/adapter.html
0.2.x～0.3.x支持，0.4.x的版本我还没测试，如果有问题可以提给我

**Comment by maxtcarry** [comment]
好的   我瞅瞅

**Comment by chenzhuo1992** [comment]
群还没有。这个月底之前会把物理引擎、webgl、自定义插件和几个demo补齐。

**Comment by togoog** [comment]
楼主加油，看好楼主的轻量级。最好是把微信小游戏适配直接做进去。

**Comment by chenzhuo1992** [comment]
@togoog 是做进去的，引一个js文件即可。这个周六或者周日发布。

**Comment by chenzhuo1992** [comment]
已经支持微信小游戏
